[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["**/*.ts", "**/*.js", "package.json"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = { default = "3001" }

[[services]]
name = "gorbagana-game-server"

[[services.variables]]
name = "REDIS_URL"
value = "${{Redis.REDIS_URL}}"

[[services.variables]]
name = "CLIENT_URL"
value = "${{CLIENT_URL}}"

[[services.variables]]
name = "ALLOWED_ORIGINS"
value = "${{ALLOWED_ORIGINS}}"

[[services.variables]]
name = "GORBAGANA_RPC_URL"
value = "${{GORBAGANA_RPC_URL}}"