[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
gorbagana_game = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.gorbagana]
gorbagana_game = "ASRy3mvEcwWzPFNZVJubdnm6XhMTdjSYPPZ48rexm3hB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[clusters.gorbagana]
url = "https://rpc.gorbagana.wtf/"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgrade_authority_off = false
skip_local_validator = false

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"